# 线上配置文件
# @author 阿狸
server:
  port: 8111
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.178.160.251:3306/yy_api
    username: yy_api
    password: yjc125125
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 3
    host: localhost
    port: 6379
    timeout: 5000
    password: yyapi@redis
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
